/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ChatCompletionReq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatCompletionReqTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatCompletionReq
        //private ChatCompletionReq instance;

        public ChatCompletionReqTests()
        {
            // TODO uncomment below to create an instance of ChatCompletionReq
            //instance = new ChatCompletionReq();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatCompletionReq
        /// </summary>
        [Fact]
        public void ChatCompletionReqInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatCompletionReq
            //Assert.IsType<ChatCompletionReq>(instance);
        }

        /// <summary>
        /// Test the property 'MaxTokens'
        /// </summary>
        [Fact]
        public void MaxTokensTest()
        {
            // TODO unit test for the property 'MaxTokens'
        }

        /// <summary>
        /// Test the property 'Temperature'
        /// </summary>
        [Fact]
        public void TemperatureTest()
        {
            // TODO unit test for the property 'Temperature'
        }

        /// <summary>
        /// Test the property 'TopP'
        /// </summary>
        [Fact]
        public void TopPTest()
        {
            // TODO unit test for the property 'TopP'
        }

        /// <summary>
        /// Test the property 'Stop'
        /// </summary>
        [Fact]
        public void StopTest()
        {
            // TODO unit test for the property 'Stop'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ReqTime'
        /// </summary>
        [Fact]
        public void ReqTimeTest()
        {
            // TODO unit test for the property 'ReqTime'
        }

        /// <summary>
        /// Test the property 'TextList'
        /// </summary>
        [Fact]
        public void TextListTest()
        {
            // TODO unit test for the property 'TextList'
        }
    }
}
