# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.chat_completion_req import ChatCompletionReq

class TestChatCompletionReq(unittest.TestCase):
    """ChatCompletionReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatCompletionReq:
        """Test ChatCompletionReq
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatCompletionReq`
        """
        model = ChatCompletionReq()
        if include_optional:
            return ChatCompletionReq(
                max_tokens = None,
                temperature = 1.337,
                top_p = 1.337,
                stop = None,
                model = None,
                id = '5ffa5d5b-5faa-4f6b-bf43-5dcecf932269',
                req_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                text_list = openapi_client.models.chat_text_list.ChatTextList(
                    messages = [
                        openapi_client.models.chat_text.ChatText(
                            role = 'system', 
                            content = null, 
                            generated = '', )
                        ], )
            )
        else:
            return ChatCompletionReq(
                text_list = openapi_client.models.chat_text_list.ChatTextList(
                    messages = [
                        openapi_client.models.chat_text.ChatText(
                            role = 'system', 
                            content = null, 
                            generated = '', )
                        ], ),
        )
        """

    def testChatCompletionReq(self):
        """Test ChatCompletionReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
