/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChatText } from '../models/ChatText';
import { HttpFile } from '../http/http';

/**
* Represents a collection of messages in a conversation.
*/
export class ChatTextList {
    'messages'?: Array<ChatText>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<ChatText>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChatTextList.attributeTypeMap;
    }

    public constructor() {
    }
}

